#!/usr/bin/env sh

rm pols.svg

IM_W=600
IM_H=600

sed "s/latitude//g; s/longitude//g; s/\(\.[0-9]\{5\}\)[0-9]*/\1/g; s/},{/,/g"  pols.json |
    tr -d "\":{}[]" |
    awk '
    BEGIN {
	FS=","
	IM_W = 600
	IM_H = 600
	MAX_X=51.69187
	MIN_X=51.28675
	MAX_Y=0.33404
	MIN_Y=-0.51035
    } 
    { 
	$1 = ( IM_W * ( ($1 - MIN_X ) / ( MAX_X - MIN_X )) )
	$2 = ( IM_H * ( ($2 - MIN_Y ) / ( MAX_Y - MIN_Y )) )

	for (i = 2; i <= (NF - 1); i+=2 ) {
	    $i = ( IM_H * ( ($i - MIN_Y ) / ( MAX_Y - MIN_Y )) )
	}
	for (i = 3; i <= (NF - 1); i+=2 ) {
	    $i = ( IM_W * ( ($i - MIN_X ) / ( MAX_X - MIN_X )) )
	    sub(/^/, "L", $i)
	}

	sub(/^/, "d=\" M", $1)
	sub(/$/, "Z\"", $NF)
	print $0
    }
    ' >> svgs
    

sed "s/\"id\":/id=/g; s/\"name\":/title=/g; s/},{/\t/g"  nh.json |
    tr -d ":[]{}" |
    tr -t ",\t" " \n" >> nh
    

printf  "<svg width=\"$IM_W\" height=\"$IM_H\">\n<g>\n" >> pols.svg
paste nh svgs | sed 's/^/<path /g; s/$/ \/>/g' >> pols.svg
printf  "</g>\n</svg>\n" >> pols.svg

rm svgs nh
